-- Role model (run as SECURITYADMIN / USERADMIN). Status: authored, not yet executed.
--
--   BOMG_ADMIN    - owns objects, runs provisioning
--   BOMG_ENGINEER - pipeline + dbt: read/write RAW..MARTS, read GROUND_TRUTH
--   BOMG_APP      - API service account: read CORE/QUALITY/MARTS, write QUALITY remediation tables
--   BOMG_ANALYST  - Power BI / analysts: read MARTS only
--   Note: GROUND_TRUTH is readable only by BOMG_ADMIN and evaluation jobs.

CREATE ROLE IF NOT EXISTS BOMG_ADMIN;
CREATE ROLE IF NOT EXISTS BOMG_ENGINEER;
CREATE ROLE IF NOT EXISTS BOMG_APP;
CREATE ROLE IF NOT EXISTS BOMG_ANALYST;

GRANT ROLE BOMG_ENGINEER TO ROLE BOMG_ADMIN;
GRANT ROLE BOMG_APP      TO ROLE BOMG_ADMIN;
GRANT ROLE BOMG_ANALYST  TO ROLE BOMG_ADMIN;
GRANT ROLE BOMG_ADMIN    TO ROLE SYSADMIN;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE BOMG_WH_XS TO ROLE BOMG_ENGINEER;
GRANT USAGE ON WAREHOUSE BOMG_WH_XS TO ROLE BOMG_APP;
GRANT USAGE ON WAREHOUSE BOMG_WH_XS TO ROLE BOMG_ANALYST;
GRANT USAGE ON WAREHOUSE BOMG_WH_ML TO ROLE BOMG_ENGINEER;

-- Database / schema usage
GRANT USAGE ON DATABASE BOM_GUARDIAN TO ROLE BOMG_ENGINEER;
GRANT USAGE ON DATABASE BOM_GUARDIAN TO ROLE BOMG_APP;
GRANT USAGE ON DATABASE BOM_GUARDIAN TO ROLE BOMG_ANALYST;

GRANT USAGE ON ALL SCHEMAS IN DATABASE BOM_GUARDIAN TO ROLE BOMG_ENGINEER;
GRANT USAGE ON SCHEMA BOM_GUARDIAN.CORE    TO ROLE BOMG_APP;
GRANT USAGE ON SCHEMA BOM_GUARDIAN.QUALITY TO ROLE BOMG_APP;
GRANT USAGE ON SCHEMA BOM_GUARDIAN.MARTS   TO ROLE BOMG_APP;
GRANT USAGE ON SCHEMA BOM_GUARDIAN.MARTS   TO ROLE BOMG_ANALYST;

-- Engineer: full DML on pipeline schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BOM_GUARDIAN.RAW     TO ROLE BOMG_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BOM_GUARDIAN.STAGING TO ROLE BOMG_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BOM_GUARDIAN.CORE    TO ROLE BOMG_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BOM_GUARDIAN.QUALITY TO ROLE BOMG_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA BOM_GUARDIAN.MARTS   TO ROLE BOMG_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA BOM_GUARDIAN.GROUND_TRUTH TO ROLE BOMG_ENGINEER;

-- App: read analytical layers, write only remediation/audit tables (granted per table
-- once QUALITY tables exist; keep default deny)
GRANT SELECT ON ALL TABLES IN SCHEMA BOM_GUARDIAN.CORE    TO ROLE BOMG_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA BOM_GUARDIAN.QUALITY TO ROLE BOMG_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA BOM_GUARDIAN.MARTS   TO ROLE BOMG_APP;

-- Analyst: marts only
GRANT SELECT ON ALL TABLES IN SCHEMA BOM_GUARDIAN.MARTS TO ROLE BOMG_ANALYST;

-- Future grants keep new tables covered
GRANT SELECT ON FUTURE TABLES IN SCHEMA BOM_GUARDIAN.MARTS TO ROLE BOMG_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BOM_GUARDIAN.CORE    TO ROLE BOMG_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BOM_GUARDIAN.QUALITY TO ROLE BOMG_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BOM_GUARDIAN.MARTS   TO ROLE BOMG_APP;
