-- Full teardown (run as SYSADMIN; roles as SECURITYADMIN). DESTRUCTIVE.

DROP DATABASE IF EXISTS BOM_GUARDIAN;
DROP WAREHOUSE IF EXISTS BOMG_WH_XS;
DROP WAREHOUSE IF EXISTS BOMG_WH_ML;

DROP ROLE IF EXISTS BOMG_ANALYST;
DROP ROLE IF EXISTS BOMG_APP;
DROP ROLE IF EXISTS BOMG_ENGINEER;
DROP ROLE IF EXISTS BOMG_ADMIN;
